defaults:
  - _train
  - datasets@dataset: toy_example_1
  - _self_

model_cfg:
  hidden_sizes: [128, 128, 128]
  seed: 1
  activation: gelu

train_cfg:
  num_epochs: 50
  learning_rate: 1e-3
  batch_size: 128
  weight_decay: 0.0
