features:
  - age
  - first_hosp_stay
  - first_icu_stay
  - adult_icu
  - eth_asian
  - eth_black
  - eth_hispanic
  - eth_other
  - eth_white
  - admType_ELECTIVE
  - admType_EMERGENCY
  - admType_NEWBORN
  - admType_URGENT
  - heartrate_min
  - heartrate_max
  - heartrate_mean
  - sysbp_min
  - sysbp_max
  - sysbp_mean
  - diasbp_min
  - diasbp_max
  - diasbp_mean
  - meanbp_min
  - meanbp_max
  - meanbp_mean
  - resprate_min
  - resprate_max
  - resprate_mean
  - tempc_min
  - tempc_max
  - tempc_mean
  - spo2_min
  - spo2_max
  - spo2_mean
  - glucose_min
  - glucose_max
  - glucose_mean
  - aniongap
  - albumin
  - bicarbonate
  - bilirubin
  - creatinine
  - chloride
  - glucose
  - hematocrit
  - hemoglobin
  - lactate
  - magnesium
  - phosphate
  - platelet
  - potassium
  - ptt
  - inr
  - pt
  - sodium
  - bun
  - wbc
name: mimic3
numeric_scaler: minmax
target_names:
  - mort_icu
test_ratio: 0.2
train_ratio: 0.6
type: classification
val_ratio: 0.2
