features:
  - age
  - sex
  - dzclass
  - numco
  - edu
  - income
  - scoma
  - race
  - hday
  - diabetes
  - dementia
  - ca
  - meanbp
  - wblc
  - hrt
  - resp
  - temp
  - pafi
  - alb
  - bili
  - crea
  - sod
  - ph
  - glucose
  - bun
  - urine
  - adlp
  - adls
  - adlsc
name: support2
numeric_scaler: minmax
target_names:
  - hospdead
test_ratio: 0.2
train_ratio: 0.6
type: classification
val_ratio: 0.2
