n_datapoints: 10000
name: uncorrelated_but_dependent
train_ratio: 0.7
val_ratio: 0.2
test_ratio: 0.1
n_features: 2
target_names: [target_0]
numeric_scaler: minmax
type: regression

# dummy vars
weights: [0.0]
sampling_correlation: 0.0
